---
- name: Configure nginx as reverse proxy for Django app
  hosts: ec2-instance
  become: yes
  gather_facts: no
  tasks:
    - name: Configure nginx as reverse proxy
      raw: |
        sudo tee /etc/nginx/conf.d/django.conf > /dev/null << 'EOF'
        server {
            listen 80;
            server_name 52.55.35.4;

            location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }

            location /static/ {
                alias /opt/django-app/static/;
                expires 30d;
                add_header Cache-Control "public, immutable";
            }

            location /media/ {
                alias /opt/django-app/media/;
                expires 30d;
                add_header Cache-Control "public, immutable";
            }

            # Health check endpoint
            location /health/ {
                proxy_pass http://127.0.0.1:8000/health/;
                access_log off;
                add_header Cache-Control "no-cache, no-store, must-revalidate";
                add_header Pragma "no-cache";
                add_header Expires "0";
            }
        }
        EOF
      changed_when: false

    - name: Remove default nginx site
      raw: sudo rm -f /etc/nginx/conf.d/default.conf
      changed_when: false

    - name: Test nginx configuration
      raw: sudo nginx -t
      changed_when: false

    - name: Reload nginx
      raw: sudo /etc/init.d/nginx reload
      changed_when: false

    - name: Display nginx status
      raw: sudo /etc/init.d/nginx status
      register: nginx_status
      changed_when: false

    - name: Show nginx status
      debug:
        var: nginx_status.stdout_lines 