---
- name: Configure Processing Service
  hosts: processing_service_ec2
  become: true
  tasks:
    - name: Install Python 3.8 and set as default
      ansible.builtin.shell: |
        sudo amazon-linux-extras install python3.8 -y
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
        sudo update-alternatives --set python3 /usr/bin/python3.8
      args:
        creates: /usr/bin/python3.8

    - name: Install Git
      ansible.builtin.yum:
        name: git
        state: present
        use_backend: dnf4

    - name: Create application directory
      ansible.builtin.file:
        path: /opt/processing-service
        state: directory
        mode: '0755'

    - name: Copy processing service files
      ansible.builtin.copy:
        src: ../
        dest: /opt/processing-service

    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: /opt/processing-service/requirements.txt
        executable: /usr/bin/pip3.8

    - name: Install Redis (for Celery broker)
      ansible.builtin.yum:
        name: redis
        state: present
        use_backend: dnf4

    - name: Start Redis service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes

    - name: Create systemd service for FastAPI app
      ansible.builtin.template:
        src: fastapi.service.j2
        dest: /etc/systemd/system/fastapi.service
      notify: Restart FastAPI

    - name: Create systemd service for Celery worker
      ansible.builtin.template:
        src: celery.service.j2
        dest: /etc/systemd/system/celery.service
      notify: Restart Celery

    - name: Start and enable FastAPI service
      ansible.builtin.service:
        name: fastapi
        state: started
        enabled: yes

    - name: Start and enable Celery service
      ansible.builtin.service:
        name: celery
        state: started
        enabled: yes

  handlers:
    - name: Restart FastAPI
      ansible.builtin.service:
        name: fastapi
        state: restarted

    - name: Restart Celery
      ansible.builtin.service:
        name: celery
        state: restarted
