name: Deploy Django App to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  EC2_HOST: 52.55.35.4
  EC2_USER: ec2-user
  ANSIBLE_DIR: Week2/ec2-layer/ansible

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Debug connectivity
      run: |
        echo "Testing connectivity to ${{ env.EC2_HOST }}"
        ping -c 3 ${{ env.EC2_HOST }} || echo "Ping failed"
        nc -zv ${{ env.EC2_HOST }} 22 || echo "Port 22 connection failed"
        echo "Runner IP: $(curl -s ifconfig.me)"

    - name: Test SSH connection with verbose output
      run: |
        ssh -v -o StrictHostKeyChecking=no -o ConnectTimeout=30 ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "echo 'SSH connection successful'" || echo "SSH connection failed"

    - name: Test Ansible connection
      run: |
        cd ${{ env.ANSIBLE_DIR }}
        ansible all -m ping -i inventory.yml -vvv

    - name: Run Ansible deployment
      run: |
        cd ${{ env.ANSIBLE_DIR }}
        echo "Current directory: $(pwd)"
        echo "Files in current directory: $(ls -la)"
        ansible-playbook deploy_django.yml -i inventory.yml

    - name: Wait for deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 60

    - name: Verify deployment
      run: |
        # Test Django app
        curl -f -I http://${{ env.EC2_HOST }}/api/users/ || exit 1

    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
          echo "🌐 Django app is running at http://${{ env.EC2_HOST }}"
          echo "🔧 Admin interface: http://${{ env.EC2_HOST }}/api/users/"
        else
          echo "❌ Deployment failed!"
        fi
